// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfZ9YDkCBbkURcm21A4u6QQ_ZFBby9RI0',
    appId: '1:250872293296:web:9ff3e76d003af0e2af1875',
    messagingSenderId: '250872293296',
    projectId: 'electro-daimn-house',
    authDomain: 'electro-daimn-house.firebaseapp.com',
    storageBucket: 'electro-daimn-house.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGohejGQk-dKAlV3AJ73XXuzHcSVKvOoI',
    appId: '1:250872293296:android:ba7c3282e1b49609af1875',
    messagingSenderId: '250872293296',
    projectId: 'electro-daimn-house',
    storageBucket: 'electro-daimn-house.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5i1CVIKJ_e6B-1mQYMkY37jc_bJsCSAM',
    appId: '1:250872293296:ios:ed65134fd34d4e23af1875',
    messagingSenderId: '250872293296',
    projectId: 'electro-daimn-house',
    storageBucket: 'electro-daimn-house.firebasestorage.app',
    iosBundleId: 'com.example.myProfile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5i1CVIKJ_e6B-1mQYMkY37jc_bJsCSAM',
    appId: '1:250872293296:ios:ed65134fd34d4e23af1875',
    messagingSenderId: '250872293296',
    projectId: 'electro-daimn-house',
    storageBucket: 'electro-daimn-house.firebasestorage.app',
    iosBundleId: 'com.example.myProfile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfZ9YDkCBbkURcm21A4u6QQ_ZFBby9RI0',
    appId: '1:250872293296:web:0129770c1a383c9aaf1875',
    messagingSenderId: '250872293296',
    projectId: 'electro-daimn-house',
    authDomain: 'electro-daimn-house.firebaseapp.com',
    storageBucket: 'electro-daimn-house.firebasestorage.app',
  );
}
